- client/src/views/components/login/style.ts
- client/src/views/pages/Login.tsx
className 삭제
styled-component style.ts로 옮김
> refactor:style.ts for login

- client/src/views/components/UI/Layout.style.ts
- client/src/views/components/UI/molecules/button.style.tsx
- client/src/views/components/common/MyPageNav.tsx
- client/src/views/pages/CurrentChallengesPage/index.tsx
- client/src/views/pages/Mypage/index.tsx
- client/src/views/pages/Mypage/mypage.style.tsx
- client/src/views/pages/PreviousChallenges/Diary.tsx
- client/src/views/pages/PreviousChallenges/Home.tsx
- client/src/views/pages/PreviousChallenges/Morning.tsx
- client/src/views/pages/PreviousChallenges/Study.tsx
- client/src/views/pages/PreviousChallenges/index.tsx
- client/src/views/pages/RankingPage/RankingsPage.style.tsx
- client/src/views/pages/RankingPage/StampList.tsx
- client/src/views/pages/RankingPage/index.tsx
- client/src/views/pages/SettingsPage/index.tsx
> fix: rename style file for client

- client/src/store/store.ts
- client/src/views/components/UI/Layout.style.ts
- client/src/views/components/UI/atoms/static.style.tsx
- client/src/views/components/common/MyPageNav.tsx
- client/src/views/pages/CreditPage/Attributions.tsx
- client/src/views/pages/CreditPage/CreditPage.style.ts
- client/src/views/pages/CreditPage/Members.tsx
- client/src/views/pages/CreditPage/index.tsx
- client/src/views/pages/Mypage/mypage.style.tsx
- client/src/views/pages/PreviousChallenges/Home.tsx
- client/src/views/pages/PreviousChallenges/PreviousChallenges.style.ts
- client/src/views/pages/PreviousChallenges/Study.tsx
- client/src/views/pages/PreviousChallenges/index.tsx
- client/src/views/pages/RankingPage/RankingsPage.style.tsx
- client/src/views/pages/RankingPage/StampList.tsx
- client/src/views/pages/RankingPage/index.tsx
- client/src/views/pages/SignupPage/SignupPage.style.ts
+ Credit page 생성
아이콘 저작권 표시, 출처 링크 연결
스타일 컴포넌트 코드 분할, 재사용
> style: graphic attribution, interactive UI for Credit Page

- server/server/src/main/java/com/cactusvilleage/server/auth/entities/Member.java
- server/server/src/main/java/com/cactusvilleage/server/auth/entities/Status.java
- server/server/src/main/java/com/cactusvilleage/server/auth/service/CustomOAuth2UserService.java
- server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
- server/server/src/main/java/com/cactusvilleage/server/auth/web/dto/request/PlainSignupDto.java
- server/server/src/main/java/com/cactusvilleage/server/challenge/delegation/DelegationData.java
- server/server/src/main/java/com/cactusvilleage/server/challenge/entities/Challenge.java
- server/server/src/main/java/com/cactusvilleage/server/challenge/entities/Status.java
- server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
- server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/ChallengeController.java
- server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/EnrollResponseDto.java
> feat: member info send logic changed

- client/src/feature/form/index.ts
- client/src/utils/debounce.ts
- client/src/utils/validates.ts
- client/src/views/pages/LoginPage/useLoginFlows.tsx
- client/src/views/pages/SignupPage/debouncingChanges.ts
- client/src/views/pages/SignupPage/index.tsx
- client/src/views/pages/SignupPage/useSignupFlows.tsx
- client/src/views/pages/SignupPage/useSignupForm.tsx
내일 늦게 들어올 것 같아서 밤늦게 올립니다...
+ feature/form
유효성 검증에 필요한 state, reducer 추가
+ utils/debounce
디바운스 함수 생성
+ utils/validates
유효성 검증 함수 생성 (return boolean)
+ useLoginFlows
로그인 동시에 화면에 nav 출력되도록 로직 추가
+ 그외 Signup page에 있던 로직 분할, 리팩토링
의문점 디코주시길 기다리고 있겠슴다..ㅎㅎ
todo: debouncing settings page form data 
useState -> redux
> refactor: validate and debounce for Signup form input data

- server/server/build.gradle
- server/server/src/main/java/com/cactusvilleage/server/ServerApplication.java
- server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
- server/server/src/main/java/com/cactusvilleage/server/challenge/validator/ChallengeStatus.java
- server/server/src/main/java/com/cactusvilleage/server/challenge/validator/impl/ChallengeStatusValidator.java
- server/server/src/main/java/com/cactusvilleage/server/challenge/web/api/ChallengeController.java
- server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/ActiveChallengeResponseDto.java
- server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/AllChallengesResponseDto.java
`/api/v1/challenges?active=true` 진행 중인 챌린지 조회 완료
근데 챌린지랑 히스토리랑 매핑이 안 돼서 안 돌아가여
테스트는 걍 디비 직접 조작했습니다
> feat: get active challenge

- server/server/src/main/java/com/cactusvilleage/server/challenge/service/batch/ChallengeStatusJob.java
- server/server/src/main/java/com/cactusvilleage/server/challenge/service/scheduler/ChallengeStatusJobScheduler.java
> feat: sheduler time zone set

- .github/workflows/github-actions-demo.yml
- client/src/views/pages/RankingPage/KakaoShare.tsx
빌드 후 발생하는 콘솔 에러 해결하기 위해
github secrets 추가, github actions yml 파일 수정
> fix: setting up kakao env variables for github actions

- client/src/views/pages/SettingsPage/index.tsx
- client/src/views/pages/SettingsPage/useSettingsFlows.ts
- client/src/views/pages/SignupPage/index.tsx
- client/src/views/pages/SignupPage/useSignupFlows.ts
> refactor: add type for Mypage states

- client/src/views/pages/PreviousChallenges/usePreviousChallenges.ts
> fix: delete module definition for client compile error

- client/src/feature/challenge/activeChallenge.ts
- client/src/feature/challenge/previousChallenges.ts
- client/src/views/pages/CurrentChallengesPage/CurrentChallengesPage.style.tsx
- client/src/views/pages/CurrentChallengesPage/StatusGraph.tsx
- client/src/views/pages/CurrentChallengesPage/SubmitContents.tsx
- client/src/views/pages/CurrentChallengesPage/index.tsx
- client/src/views/pages/CurrentChallengesPage/useCurrentChallenge.ts
- client/src/views/pages/PreviousChallenges/usePreviousChallenges.ts
… Challenges Page
+ 서버 통신 custom hook
+ 로딩중 / 정상 응답 / 에러 핸들링
+ 데이터 rtx 저장
+ progress에 따른 graph width 5단계 분기
+ 스탬프 맵핑
> feat: custom get data hook, store state rtx, handle error for Current… 

- server/server/src/main/java/com/cactusvilleage/server/challenge/service/ChallengeService.java
- server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/ActiveInfoDto.java
- server/server/src/main/java/com/cactusvilleage/server/challenge/web/dto/response/AllInfoDto.java
ActiveInfoDto NoArgs 레벨을 바꾸지 말아주세여
> feat: initial data set when active challenge is not present

- client/src/feature/challenge/form.ts
- client/src/feature/location/index.ts
- client/src/feature/profile/user.ts
- client/src/utils/useRedirectLogoutUser.ts
- client/src/views/pages/CreditPage/index.tsx
- client/src/views/pages/CurrentChallengesPage/useCurrentChallenge.ts
- client/src/views/pages/ForgotPasswordPage/debouncedChanges.ts
- client/src/views/pages/Mypage/index.tsx
- client/src/views/pages/PreviousChallenges/usePreviousChallenges.ts
- client/src/views/pages/RankingPage/Rankers.tsx
- client/src/views/pages/RankingPage/StampList.tsx
- client/src/views/pages/RankingPage/index.tsx
- client/src/views/pages/RankingPage/rankingConstants.tsx
- client/src/views/pages/RankingPage/useRankingPage.ts
- client/src/views/pages/SettingsPage/debouncingChanges.ts
- client/src/views/pages/SettingsPage/index.tsx
- client/src/views/pages/SettingsPage/useSettingsFlows.ts
- client/src/views/pages/SettingsPage/useSettingsPageMounted.ts
- client/src/views/pages/SignupPage/index.tsx
- client/src/views/pages/SignupPage/useSignupFlows.ts
+ 비로그인 상태로 마이페이지 접근시 login page로 리디렉트
nav 감춤
+ loginStatus, Alert type export 해놨습니다
> feat: redirect non-members to Login for Mypage

- client/src/views/pages/ForgotPasswordPage/useForgotPasswordFlows.ts
- client/src/views/pages/SettingsPage/index.tsx
- client/src/views/pages/SettingsPage/useSettingsFlows.ts
> refactor: delete unnecessary conditional statement for mypage

- client/src/feature/challenge/previousChallenges.ts
- client/src/views/components/UI/Layout.style.ts
- client/src/views/pages/CurrentChallengesPage/CurrentChallengesPage.style.tsx
- client/src/views/pages/CurrentChallengesPage/SubmitContents.tsx
- client/src/views/pages/CurrentChallengesPage/index.tsx
- client/src/views/pages/PreviousChallenges/PreviousChallenges.style.ts
- client/src/views/pages/PreviousChallenges/StudyItem.tsx
+ image file path 받아와서 화면에 출력
+ todo: 지난 챌린지에서 image 출력 확인하기
+ 도장 배열도 잘 들어옵니다
> feat: get image src for Challenge Pages

- client/src/views/components/UI/Layout.style.ts
- client/src/views/pages/CurrentChallengesPage/index.tsx
- client/src/views/pages/PreviousChallenges/DiaryItem.tsx
- client/src/views/pages/PreviousChallenges/MorningItem.tsx
- client/src/views/pages/PreviousChallenges/StudyItem.tsx
- client/src/views/pages/RankingPage/Rankers.tsx
- client/src/views/pages/RankingPage/index.tsx
- client/src/views/pages/RankingPage/useRankingPage.ts
+ error messge, default message 한꺼번에 나오지 않게 변경
> feat: change error, default status message for Mypage

- server/server/src/main/java/com/cactusvilleage/server/auth/service/MemberService.java
- server/server/src/main/java/com/cactusvilleage/server/global/exception/ExceptionCode.java
- server/server/src/main/java/com/cactusvilleage/server/global/infra/email/impl/AwsSesSender.java
> feat: email send check logic added when recovery password

- client/src/views/pages/RankingPage/Rankers.tsx
- client/src/views/pages/RankingPage/index.tsx
+ 축하메세지 출력 조건 수정
+ 카카오 공유는 개발 환경 클라이언트에서 못쓴대서 일단 삭제ㅠㅠ
> fix: status message, kakao error for Rankings page

- client/src/views/components/mainpage/todayChallFunctions.tsx
- client/src/views/pages/LoginPage/useLoginFlows.tsx
> fix:delete console.log

- client/src/views/pages/CurrentChallengesPage/SubmitContents.tsx
- client/src/views/pages/SettingsPage/useSettingsFlows.ts
회원정보 수정시 에러코드 401을 응답받은 유저는 클라이언트에서 logout시킨다.
> refactor: handle response error code 401 for Settings page

- client/src/utils/reissue.ts
리이슈때문에 로그인, 회원가입, 인트로에서 로그인으로 리다이렉트되는 문제 수정
> fix:fix rendering err due to reissue for client

- client/src/views/pages/SettingsPage/useSettingsFlows.ts
회원정보 수정시 dispatch username 전달인자 변경
> fix: change argument for dispatch username

- client/src/views/pages/SettingsPage/useSettingsPageMounted.ts
> fix: initial state for OAuth login user edit form

- .github/workflows/github-actions-demo.yml
> fix: setting up default branch for github actions

- client/src/views/pages/RankingPage/index.tsx
카카오톡으로 공유하기 삭제
나중에 env 설정 다시 할 것...
> fix: delete kakaoShare button for RankingPage

- server/server/src/main/java/com/cactusvilleage/server/auth/repository/RefreshTokenRepository.java
> fix: fix npe when findall in refresh token repo (redis)

- server/server/src/main/java/com/cactusvilleage/server/ServerApplication.java
https://stackoverflow.com/questions/48379229/redis-expired-indexes-are-not-deleted
https://stackoverflow.com/questions/56181590/redis-still-returns-null-entries-even-when-they-are-expired
https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/RedisKeyValueAdapter.EnableKeyspaceEvents.html
> feat: redis not caching null value when expired (by ttl)
